### ISSUE TITLE
Toggle for certain period of time

### ISSUE THREAD

**Issue by beauwilliams** [bignimbus/you-are-here.vim#7]
This plugin looks really cool!

Nice to have this basic information at a glance to help orient yourself

I was going to suggest an added feature to the toggle where we could perhaps toggle the popups for a certain period of time. 

For example when cycling through splits you-are-here will pop up to help you get to the right split, and then go away shortly after you stop cycling.

**Comment by bignimbus** [comment]
@beauwilliams this is a cool idea and should be possible to achieve in the current version of `you-are-here.vim`.  Since the user can call `you_are_here#Toggle` arbitrarily, it shouldn't be too difficult to put that on some sort of timer.  Do you think it might be a good first step to add a suggested `.vimrc` addition for this functionality?

**Comment by beauwilliams** [comment]
Thanks for the suggestion @bignimbus :) Will give this a shoot in the evening

**Comment by bignimbus** [comment]
@beauwilliams  looks like #9 fixed this!

**Comment by beauwilliams** [comment]
Woah, too quick guys :D
